CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;

ALTER TABLE public.social_posts
  ADD COLUMN IF NOT EXISTS recurring_rule jsonb DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS score_data jsonb DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS retry_count int NOT NULL DEFAULT 0;
